#!/bin/sh

# windowchef (best wm) configuration

. $XDG_RUNTIME_DIR/xcolors
. $XDG_RUNTIME_DIR/xenv

waitron wm_config border_width ${BORDER_WIDTH}
waitron wm_config internal_border_width 1
waitron wm_config color_focused "$(echo ${xres_background} | tr -d '#')"
waitron wm_config color_unfocused "$(echo ${xres_background} | tr -d '#')"
waitron wm_config internal_color_focused "$(echo ${xres_foreground} | tr -d '#')"
waitron wm_config internal_color_unfocused "$(echo ${xres_color15} | tr -d '#')"
waitron wm_config gap_width all ${GENERAL_GAP}
waitron wm_config grid_gap_width $((${GENERAL_GAP} / 2))
waitron wm_config cursor_position middle
waitron wm_config groups_nr 9
waitron wm_config enable_resize_hints true
waitron wm_config enable_sloppy_focus false
waitron wm_config sticky_windows false
waitron wm_config enable_borders true
waitron wm_config enable_last_window_focusing true
waitron wm_config apply_settings true
waitron wm_config replay_click_on_focus true
waitron wm_config pointer_actions move resize_side resize_corner
waitron wm_config pointer_modifier super
waitron wm_config click_to_focus any
