#!/bin/sh

. $XDG_RUNTIME_DIR/xcolors

cat <<CONF
[global]
follow = "mouse"
geometry = "512x5-8+8"
shrink = true
word_wrap = true
separator_height = 2
padding = 8
horizontal_padding = 8
frame_width = 2
frame_color = "$xres_foreground"
separator_color = frame
font = misc fixed 8
markup = full
format = "<b>%s</b> %p\n%b"
show_age_threshold = 60
dmenu = "$(which dmenu)"
browser = "$(which ${BROWSER})"
icon_position = left
icon_path = "/usr/share/icons/Moka/16x16/status/:/usr/share/icons/Moka/16x16/devices:/usr/share/icons/Faba/48x48/notifications/"

[shortcuts]
close = ctrl+space
close_all = ctrl+shift+space
history = ctrl+grave
context = ctrl+shift+period

[urgency_low]
background = "$xres_background"
foreground = "$xres_foreground"
timeout = 10

[urgency_normal]
background = "$xres_background"
foreground = "$xres_foreground"
timeout = 10

[urgency_critical]
background = "$xres_foreground"
foreground = "$xres_background"
timeout = 0
CONF
