#!/bin/sh

. $XDG_RUNTIME_DIR/xcolors

cat <<CONF
[global]
follow = "mouse"
geometry = "0x5-4+4"
separator_height = 2
padding = 8
horizontal_padding = 8
frame_width = 2
frame_color = "$xres_foreground"
separator_color = frame
font = Misc Fixed 8
markup = full
format = "<u>%s</u> %p\n%b"
show_age_threshold = 60
dmenu = "$(which dmenu)"
browser = "$(which ${BROWSER})"
icon_position = left

[shortcuts]
close = ctrl+space
close_all = ctrl+shift+space
history = ctrl+grave
context = ctrl+shift+period

[urgency_low]
background = "$xres_background"
foreground = "$xres_foreground"
timeout = 10

[urgency_normal]
background = "$xres_background"
foreground = "$xres_foreground"
timeout = 10

[urgency_critical]
background = "$xres_foreground"
foreground = "$xres_background"
timeout = 0
CONF
