#!/bin/sh

. $XDG_RUNTIME_DIR/xcolors

cat <<COLORS
	"$xres_color0",
	"$xres_color1",
	"$xres_color2",
	"$xres_color3",
	"$xres_color4",
	"$xres_color5",
	"$xres_color6",
	"$xres_color7",
	"$xres_color8",
	"$xres_color9",
	"$xres_color10",
	"$xres_color11",
	"$xres_color12",
	"$xres_color13",
	"$xres_color14",
	"$xres_color15",
	[255] = 0,
	"$xres_foreground",
	"$xres_background",
COLORS
