#!/bin/sh -x

if [ -f $HOME/.Xresources ]; then
	xrdb $HOME/.Xresources
	printxcolors > $XDG_RUNTIME_DIR/xcolors
else
	echo "Cannot load X resources." && exit 1
fi

mkdir -pv $HOME/.config/dunst && gendunstrc > $HOME/.config/dunst/dunstrc
mkdir -pv $HOME/.config/zathura && genzathurarc > $HOME/.config/zathura/zathurarc
mkdir -pv $HOME/.config/i3status && geni3statusconfig > $HOME/.config/i3status/config
