#!/bin/bash

# Simple X bar.

source $XDG_RUNTIME_DIR/xcolors
source $XDG_RUNTIME_DIR/xenv

format_good() {
	echo -e "%{F${xres_color2}}${1}%{F-}"
}

format_bad() {
	echo -e "%{F${xres_color1}}${1}%{F-}"
}

format_accent() {
	echo -e "%{F${xres_color6}}${1}%{F-}"
}

get_volume() {
	if $(ponymix --output is-muted); then
		echo -e "$(format_bad '\ue052') Muted"
	else
		echo -e "$(format_accent '\ue051') $(ponymix --output get-volume)%%"
	fi
}

get_battery() {
	local dir
	local status
	local value

	dir="/sys/class/power_supply/BAT0"
	status="$(cat ${dir}/status)"
	value="$(cat ${dir}/capacity)"

	if [[ "$status" == "Charging" ]]; then
		echo -e "$(format_good '\ue033') ${value}%%"
	elif [[ "$status" == "Full" ]]; then
		echo -e "$(format_good '\ue09e') Full"
	else
		if [[ "$value" -le "15" ]]; then
			echo -e "$(format_bad '\ue031') ${value}%%"
		elif [[ "$value" -le "50" ]]; then
			echo -e "$(format_accent '\ue032') ${value}%%"
		else
			echo -e "$(format_accent '\ue033') ${value}%%"
		fi
	fi
}

get_network() {
	local ssid
	ssid="$(iw wlp1s0 info | grep ssid | awk '{print $2}')"

	if [[ -z "$ssid" ]]; then
		echo -e "$(format_bad '\ue0f0') Offline"
	else
		echo -e "$(format_accent '\ue0f0') ${ssid}"
	fi
}

get_brightness() {
	echo -e "$(format_accent '\ue26e') $(printf '%.0f%%%%' $(light))"
}

get_date() {
	echo -e "$(format_accent '\ue015') $(date '+%a %d %b %R')"
}

while :; do
	echo -e "%{c}$(get_volume)  $(get_brightness)  $(get_battery)  $(get_network)  $(get_date)"
	sleep 2
done | lemonbar -db -n sxbar\
	-g ${BAR_WIDTH}x${BAR_HEIGHT}+${BAR_X}+${BAR_Y}\
	-f "-uw-ttyp0-medium-r-normal--11-100-75-75-c-60-iso8859-1"\
	-f "-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1"\
	-B "${xres_background}" -F "${xres_foreground}"
